services:
  dockerlock:
    image: gloriayi/maternal-health-risk-classifier:bc436f2
    container_name: dockerlock
    ports:
      - "8886:8888"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true